version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "cypress",
    "jest"
  ]